# Generated by Django 3.1.3 on 2021-01-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitute', models.FloatField(default=0)),
                ('longitute', models.FloatField(default=0)),
                ('ph', models.FloatField(blank=True, default=None, null=True)),
                ('temp', models.FloatField(blank=True, default=None, null=True)),
                ('date_captured', models.DateTimeField(blank=True, default=None, null=True)),
                ('ecological_status', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('score_by_insect', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('river_id', models.AutoField(primary_key=True, serialize=False)),
                ('river_code', models.CharField(max_length=200, unique=True)),
                ('river_name', models.CharField(max_length=200)),
                ('river_catchments_code', models.CharField(max_length=20)),
                ('river_catchments', models.CharField(max_length=200)),
                ('latitute', models.FloatField(default=0)),
                ('longitute', models.FloatField(default=0)),
                ('local_authority', models.CharField(max_length=200)),
                ('water_body_category', models.CharField(max_length=200)),
                ('protected_area', models.CharField(max_length=20, null=True)),
                ('transboundary', models.CharField(max_length=20)),
                ('canal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aquality_server.login_account')),
                ('full_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('user_group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=200)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquality_server.data')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='river',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquality_server.river'),
        ),
    ]
