# Generated by Django 3.1.3 on 2020-11-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
