# Generated by Django 3.1.3 on 2020-12-08 23:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='langitute',
        ),
        migrations.RemoveField(
            model_name='data',
            name='longitute',
        ),
        migrations.AddField(
            model_name='data',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, null=True, srid=4326),
        ),
    ]
