# Generated by Django 3.1.3 on 2021-01-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='latitute',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitute',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='river',
            name='latitute',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='river',
            name='longitute',
            field=models.FloatField(default=0, null=True),
        ),
    ]
