# Generated by Django 3.1.3 on 2021-01-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0002_auto_20210106_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='latitute',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='longitute',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='river',
            old_name='latitute',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='river',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
