# Generated by Django 3.1.3 on 2020-11-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0002_auto_20201117_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='data_id',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='user_account',
            old_name='user_id',
            new_name='user_account',
        ),
    ]
