# Generated by Django 3.1.3 on 2020-11-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0003_auto_20201117_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('river_id', models.AutoField(primary_key=True, serialize=False)),
                ('river_code', models.CharField(max_length=200)),
                ('river_name', models.CharField(max_length=200)),
                ('river_catchments', models.CharField(max_length=200)),
                ('longitute', models.FloatField()),
                ('langitute', models.FloatField()),
                ('local_authority', models.CharField(max_length=200)),
                ('water_body_category', models.CharField(max_length=200)),
                ('protected_area', models.BooleanField()),
                ('area', models.FloatField()),
                ('length', models.FloatField()),
                ('transboundary', models.FloatField()),
                ('canal', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='date_captured',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ecological_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='langitute',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='longitute',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ph',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='score_by_insect',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='temp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='river',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquality_server.river'),
        ),
    ]
