# Generated by Django 3.1.3 on 2021-01-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0004_auto_20210117_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='login_account',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
