# Generated by Django 3.1.3 on 2020-11-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0004_auto_20201117_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='river_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
