# Generated by Django 3.1.3 on 2020-11-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0005_auto_20201123_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='area',
        ),
        migrations.RemoveField(
            model_name='river',
            name='length',
        ),
        migrations.AlterField(
            model_name='river',
            name='canal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='river',
            name='protected_area',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='river',
            name='transboundary',
            field=models.CharField(max_length=20),
        ),
    ]
