# Generated by Django 3.1.3 on 2020-11-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0006_auto_20201123_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='protected_area',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
