# Generated by Django 3.1.3 on 2020-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0008_auto_20201124_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='river_catchments_code',
            field=models.CharField(max_length=20),
        ),
    ]
