# Generated by Django 3.1.3 on 2021-01-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0011_insect_insect_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsectGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='insect',
            name='insect_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquality_server.insectgroup'),
        ),
    ]
