# Generated by Django 3.1.3 on 2021-01-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0012_auto_20210126_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(null=True, upload_to='insect-img'),
        ),
    ]
