# Generated by Django 3.1.3 on 2021-01-26 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0013_auto_20210126_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHistoryImageImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(null=True, upload_to='data-insect-img')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquality_server.data')),
            ],
        ),
        migrations.CreateModel(
            name='InsectImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(null=True, upload_to='insect-img')),
                ('insect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquality_server.insect')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
