# Generated by Django 3.1.3 on 2021-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0014_auto_20210126_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='insect',
            name='insect_image_path',
            field=models.ImageField(null=True, upload_to='insect-img'),
        ),
        migrations.DeleteModel(
            name='InsectImage',
        ),
    ]
