# Generated by Django 3.1.5 on 2021-01-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0015_auto_20210127_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRecord',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_date', models.DateTimeField(auto_now_add=True)),
                ('sample_score', models.IntegerField()),
                ('sample_ph', models.FloatField()),
                ('sample_tmp', models.FloatField()),
                ('sample_river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquality_server.river')),
                ('sample_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aquality_server.user_account')),
            ],
        ),
        migrations.CreateModel(
            name='SampleRecordInsectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insect_number', models.IntegerField()),
                ('sample_record_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquality_server.samplerecord')),
                ('sample_record_insect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquality_server.insect')),
            ],
        ),
    ]
