# Generated by Django 3.1.5 on 2021-01-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0017_auto_20210129_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleRecordInsectDetails',
            new_name='SampleRecordInsectDetail',
        ),
    ]
