# Generated by Django 3.1.3 on 2021-01-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0007_auto_20210120_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Account',
        ),
    ]
