# Generated by Django 3.1.3 on 2021-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0009_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('insect_id', models.AutoField(primary_key=True, serialize=False)),
                ('insect_name', models.CharField(max_length=200, unique=True)),
                ('insect_group', models.CharField(max_length=50)),
            ],
        ),
    ]
