# Generated by Django 3.1.5 on 2021-01-29 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aquality_server', '0016_samplerecord_samplerecordinsectdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerecord',
            name='sample_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='samplerecordinsectdetails',
            unique_together={('sample_record_data', 'sample_record_insect')},
        ),
    ]
